title: Humanoid Path Planner
description: Software for Motion and Manipulation Planning
baseurl: "/hpp-doc"
github-url: "https://github.com/humanoid-path-planner/hpp-doc"
apidoc-url: "https://gepettoweb.laas.fr/hpp"
remote_theme: Gepetto/jekyll-theme
markdown: kramdown

category_list:
  - name: Getting Started
    icon: graduation-cap
  - name: Documentation
    icon: book
    links:
      - name: Presentation
        url: https://humanoid-path-planner.github.io/hpp-doc/presentation/presentation.pdf
      - name: API documentation
        url: https://humanoid-path-planner.github.io/hpp-doc/documentation.html
  - name: Development
    icon: wrench
    links:
      - name: View on Github
        url: https://github.com/humanoid-path-planner/hpp-doc
  - name: Support
    icon: question-circle
